server:
  port: 8088
  servlet:
    context-path: ''
spring:
  datasource:
    url: jdbc:mysql://server.internal.ceeg-global.com/mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: db
    password: db_system
#    url: jdbc:mysql://localhost:3306/csun?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: zheng
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      max-lifetime: 1800000
      connection-test-query: select 1
  redis:
    host: server.internal.ceeg-global.com
    port: 6379
    database: 0
  messages:
    basename: i18n/csun/messages
    encoding: UTF-8
#  mvc:
#    static-path-pattern: /static/**
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: false
            paths: /**
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
      additional-paths: src/**
#logging:
#  file:
#    name: logs/app.log
#  level:
#    root: ERROR
#debug: true

#mybatis配置
#
###########################################################
mybatis:
  type-aliases-package: com.csun.mall.pojo #所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml #mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志打印
############################################################
#
#mybatismapper配置
#
############################################################
#通用Mapper配置
mapper:
  mappers: com.csun.mall.common.base.BaseMapper
  not-empty: false    #在进行数据库操作的时候，判断表达式 username ！=null，是否追加usern ！=''
  identity: MYSQL

logging:
  level:
    com.csun.mall.mapper: DEBUG