server:
  port: 8088
  servlet:
    context-path: ''
spring:
  datasource:
#    url: jdbc:mysql://test.internal.ceeg-global.com:3306/mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: db
#    password: db_system
    url: jdbc:mysql://localhost:3306/csun1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zheng
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      max-lifetime: 1800000
      connection-test-query: select 1
  redis:
    host: 10.8.8.52
#    host: 47.111.143.81
    port: 6379
    database: 0
  messages:
    basename: i18n/csun/messages
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: false
            paths: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/**
  mail:
#    gmail
#    host: smtp.gmail.com
#    port: 465
#    username: yimcarson@gmail.com
#    password: ****************
#    qq
#    host: smtp.qq.com
#    port: 587
#    username: yimcarson@qq.com
#    password: ************
    # 163
    host: smtp.163.com
    port:
    username: jokerni53@163.com
    password: LHQKCZUMBUEUOQMZ
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false


#mybatis配置
#
###########################################################
mybatis:
  type-aliases-package: com.csun.mall.pojo #所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml #mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志打印
############################################################
#
#mybatismapper配置
#
############################################################
#通用Mapper配置
mapper:
  mappers: com.csun.mall.common.base.BaseMapper
  not-empty: false    #在进行数据库操作的时候，判断表达式 username ！=null，是否追加usern ！=''
  identity: MYSQL

logging:
  level:
    com.csun.mall.mapper: DEBUG


oss:
  access_key_id: LTAI5tBWLb9LA9wosbLzp2cB
  access_key_secret: 56ss4aNcqfcDU7HVcRHz4gzFLbbRBF
  endpoint: oss-cn-beijing.aliyuncs.com


